version: '3'

services:
  reader-api:
    container_name: reader-api
    build:
      context: .
      dockerfile: ./configs/data-reader-service/Dockerfile
    networks:
      - proxy-net
    restart: always

  writer-api:
    container_name: writer-api
    build:
      context: .
      dockerfile: ./configs/data-writer-service/Dockerfile
    networks:
      - proxy-net
    # ports:
    #   - 4001:4001
    restart: always

  user-api-1:
    container_name: user-api-1
    build:
      context: .
      dockerfile: ./configs/user-service/Dockerfile
    networks:
      - proxy-net
    restart: always
  
  user-api-2:
    container_name: user-api-2
    build:
      context: .
      dockerfile: ./configs/user-service/Dockerfile
    networks:
      - proxy-net
    restart: always

  api-gateway:
    container_name: api-gateway
    build: 
      context: .
      dockerfile: ./configs/gateway/Dockerfile
    networks:
      - proxy-net
    ports:
      - 80:80
    #  - 443:443
    restart: always
    #deploy:
    #  mode: replicated
    #  replicas: 2
      #endpoint_mode: voip

networks:
  proxy-net:
    name: proxy-net
    #driver: default
