version: '3'

services:
  reader-api-kea-1:
    container_name: reader-api-kea-1
    env_file:
      - ./configs/kea/data-reader-service/reader.env
    build:
      context: .
      dockerfile: ./configs/kea/data-reader-service/Dockerfile
    networks:
      - proxy-net
    restart: always
    depends_on:
      kea-db:
        condition: service_healthy


  writer-api-kea-1:
    container_name: writer-api-kea-1
    env_file:
      - ./configs/kea/data-writer-service/writer.env
    build:
      context: .
      dockerfile: ./configs/kea/data-writer-service/Dockerfile
    networks:
      - proxy-net
    restart: always
    depends_on:
      kea-db:
        condition: service_healthy

  user-api-1:
    container_name: user-api-1
    build:
      context: .
      dockerfile: ./configs/user-service/Dockerfile
    networks:
      - proxy-net
    restart: always
  
  user-api-2:
    container_name: user-api-2
    build:
      context: .
      dockerfile: ./configs/user-service/Dockerfile
    networks:
      - proxy-net
    restart: always

  kea-db:
    container_name: kea-db
    build: 
      context: .
      dockerfile: ./configs/kea/data-store/Dockerfile
    env_file:  ./configs/kea/data-store/database.env
    networks:
      - proxy-net
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD --execute 'SHOW DATABASES';"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 3s
    cap_add:
      - SYS_NICE

  api-gateway:
    container_name: api-gateway
    build: 
      context: .
      dockerfile: ./configs/gateway/Dockerfile
    networks:
      - proxy-net
    ports:
      - 80:80
    #  - 443:443
    restart: always
    depends_on:
      - kea-db
      - user-api-1
      - user-api-2
      - writer-api-kea-1
      - reader-api-kea-1

networks:
  proxy-net:
    name: proxy-net
    #driver: default
